deal.II Testbench for NMOPT Laboratories: Laplacian< dim > Class Template Reference
Laplacian< dim > Class Template Reference
#include <laplacian.h>
Public Member Functions
Laplacian (const std::string &subsection_name="Poisson problem")
void initialize ()
void solve ()
void solve (const Vector< double > &rhs, Vector< double > &dst) const
void output_results (const std::string &filename="solution") const
void run ()
const SparseMatrix< double > & get_mass_matrix () const
const SparseMatrix< double > & get_system_matrix () const
const AffineConstraints< double > & get_constraints () const
const DoFHandler< dim > & get_dof_handler () const
const Vector< double > & get_system_rhs () const
const Vector< double > & get_solution () const
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
void declare_parameters (ParameterHandler &prm) override
void parse_parameters (ParameterHandler &prm) override
void make_grid ()
void setup_system ()
void assemble_system ()
Protected Attributes
Triangulation< dim > triangulation
std::unique_ptr< FE_Q< dim > > fe
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
SparseMatrix< double > system_matrix
SparseMatrix< double > mass_matrix
SparsityPattern sparsity_pattern
Vector< double > solution
Vector< double > system_rhs
unsigned int fe_degree
unsigned int global_refinements
unsigned int solver_max_iterations
double solver_tolerance
double preconditioner_relaxation
std::string grid_generator_function
std::string grid_generator_arguments
Functions::ParsedFunction< dim > diffusion_coefficient
Functions::ParsedFunction< dim > forcing_term
Functions::ParsedFunction< dim > boundary_values
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class Laplacian< dim >
Definition at line 40 of file laplacian.h.
Constructor & Destructor Documentation
Laplacian()
template<int dim> Laplacian< dim >::Laplacian (const std::string & subsection_name = "Poisson problem")
Definition at line 40 of file laplacian.cc.
References e(), and triangulation.
Member Function Documentation
assemble_system()
template<int dim> void Laplacian< dim >::assemble_system () protected
Definition at line 161 of file laplacian.cc.
References FEValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::JxW(), FEValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::shape_grad(), FEValues< int dim, int spacedim >::shape_value(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
declare_parameters()
template<int dim> void Laplacian< dim >::declare_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 60 of file laplacian.cc.
References ParameterHandler::add_parameter(), Functions::ParsedFunction< int dim >::declare_parameters(), ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
get_constraints()
template<int dim> const AffineConstraints< double > & Laplacian< dim >::get_constraints () const
Definition at line 303 of file laplacian.cc.
get_dof_handler()
template<int dim> const DoFHandler< dim > & Laplacian< dim >::get_dof_handler () const
Definition at line 312 of file laplacian.cc.
get_mass_matrix()
template<int dim> const SparseMatrix< double > & Laplacian< dim >::get_mass_matrix () const
Definition at line 285 of file laplacian.cc.
get_solution()
template<int dim> const Vector< double > & Laplacian< dim >::get_solution () const
Definition at line 330 of file laplacian.cc.
get_system_matrix()
template<int dim> const SparseMatrix< double > & Laplacian< dim >::get_system_matrix () const
Definition at line 294 of file laplacian.cc.
get_system_rhs()
template<int dim> const Vector< double > & Laplacian< dim >::get_system_rhs () const
Definition at line 321 of file laplacian.cc.
initialize()
template<int dim> void Laplacian< dim >::initialize ()
Definition at line 121 of file laplacian.cc.
make_grid()
template<int dim> void Laplacian< dim >::make_grid () protected
Definition at line 108 of file laplacian.cc.
References GridGenerator::generate_from_name_and_arguments(), and triangulation.
output_results()
template<int dim> void Laplacian< dim >::output_results (const std::string & filename = "solution") const
Definition at line 253 of file laplacian.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), and DataOut< int dim, int spacedim >::write_vtu().
parse_parameters()
template<int dim> void Laplacian< dim >::parse_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 87 of file laplacian.cc.
References ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
run()
template<int dim> void Laplacian< dim >::run ()
Definition at line 268 of file laplacian.cc.
References triangulation.
setup_system()
template<int dim> void Laplacian< dim >::setup_system () protected
Definition at line 132 of file laplacian.cc.
References VectorTools::interpolate_boundary_values(), DoFTools::make_hanging_node_constraints(), and DoFTools::make_sparsity_pattern().
solve() [1/2]
template<int dim> void Laplacian< dim >::solve ()
Definition at line 226 of file laplacian.cc.
solve() [2/2]
template<int dim> void Laplacian< dim >::solve (const Vector< double > & rhs, Vector< double > & dst) const
Definition at line 235 of file laplacian.cc.
References PreconditionSSOR< typename MatrixType >::initialize(), Vector< typename Number >::reinit(), and SolverCG< typename VectorType >::solve().
Member Data Documentation
boundary_values
template<int dim> Functions::ParsedFunction<dim> Laplacian< dim >::boundary_values protected
Definition at line 119 of file laplacian.h.
constraints
template<int dim> AffineConstraints<double> Laplacian< dim >::constraints protected
Definition at line 100 of file laplacian.h.
diffusion_coefficient
template<int dim> Functions::ParsedFunction<dim> Laplacian< dim >::diffusion_coefficient protected
Definition at line 117 of file laplacian.h.
dof_handler
template<int dim> DoFHandler<dim> Laplacian< dim >::dof_handler protected
Definition at line 97 of file laplacian.h.
fe
template<int dim> std::unique_ptr<FE_Q<dim> > Laplacian< dim >::fe protected
Definition at line 96 of file laplacian.h.
fe_degree
template<int dim> unsigned int Laplacian< dim >::fe_degree protected
Definition at line 109 of file laplacian.h.
forcing_term
template<int dim> Functions::ParsedFunction<dim> Laplacian< dim >::forcing_term protected
Definition at line 118 of file laplacian.h.
global_refinements
template<int dim> unsigned int Laplacian< dim >::global_refinements protected
Definition at line 110 of file laplacian.h.
grid_generator_arguments
template<int dim> std::string Laplacian< dim >::grid_generator_arguments protected
Definition at line 115 of file laplacian.h.
grid_generator_function
template<int dim> std::string Laplacian< dim >::grid_generator_function protected
Definition at line 114 of file laplacian.h.
mass_matrix
template<int dim> SparseMatrix<double> Laplacian< dim >::mass_matrix protected
Definition at line 103 of file laplacian.h.
preconditioner_relaxation
template<int dim> double Laplacian< dim >::preconditioner_relaxation protected
Definition at line 113 of file laplacian.h.
solution
template<int dim> Vector<double> Laplacian< dim >::solution protected
Definition at line 106 of file laplacian.h.
solver_max_iterations
template<int dim> unsigned int Laplacian< dim >::solver_max_iterations protected
Definition at line 111 of file laplacian.h.
solver_tolerance
template<int dim> double Laplacian< dim >::solver_tolerance protected
Definition at line 112 of file laplacian.h.
sparsity_pattern
template<int dim> SparsityPattern Laplacian< dim >::sparsity_pattern protected
Definition at line 104 of file laplacian.h.
system_matrix
template<int dim> SparseMatrix<double> Laplacian< dim >::system_matrix protected
Definition at line 102 of file laplacian.h.
system_rhs
template<int dim> Vector<double> Laplacian< dim >::system_rhs protected
Definition at line 107 of file laplacian.h.
triangulation
template<int dim> Triangulation<dim> Laplacian< dim >::triangulation protected
Definition at line 94 of file laplacian.h.
The documentation for this class was generated from the following files:
laplacian.h
laplacian.cc