deal.II Testbench for NMOPT Laboratories: InversePoissonKKT< dim > Class Template Reference
InversePoissonKKT< dim > Class Template Reference
#include <inverse_poisson_kkt.h>
Public Member Functions
InversePoissonKKT (const std::string &subsection_name="Inverse Poisson KKT problem")
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Static Public Attributes
static constexpr unsigned int n_blocks = 3
static constexpr unsigned int state_block = 0
static constexpr unsigned int adjoint_block = 1
static constexpr unsigned int control_block = 2
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Member Functions
void declare_parameters (ParameterHandler &prm) override
void parse_parameters (ParameterHandler &prm) override
Private Member Functions
void make_grid ()
void setup_system ()
void initialize_vectors ()
void initialize_control_mass_matrix ()
void initialize_solution ()
void assemble_system ()
BlockVector< double > assemble_residual_only (const BlockVector< double > &iterate) const
std::vector< bool > compute_lower_active_set () const
std::vector< bool > compute_upper_active_set () const
Vector< double > compute_stationarity () const
AffineConstraints< double > make_control_constraints (const std::vector< bool > &lower_active, const std::vector< bool > &upper_active) const
void solve_linearized_system (const std::vector< bool > &lower_active, const std::vector< bool > &upper_active, BlockVector< double > &update) const
void enforce_box_constraints (BlockVector< double > &iterate, const std::vector< bool > &lower_active, const std::vector< bool > &upper_active) const
void interpolate_component_function (const Function< dim > &function, const unsigned int block, BlockVector< double > &vector) const
void output_results (const BlockVector< double > &iterate, const std::vector< bool > &lower_active, const std::vector< bool > &upper_active, const std::string &filename) const
std::string output_iteration (const unsigned int iteration, const BlockVector< double > &iterate, const std::vector< bool > &lower_active, const std::vector< bool > &upper_active) const
types::global_dof_index control_global_offset () const
Private Attributes
Triangulation< dim > triangulation
std::unique_ptr< FESystem< dim > > fe
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
BlockSparsityPattern sparsity_pattern
BlockSparseMatrix< double > system_matrix
BlockVector< double > current_solution
BlockVector< double > system_rhs
BlockVector< double > residual
BlockVector< double > lower_bound
BlockVector< double > upper_bound
BlockVector< double > reference_coefficient_vector
BlockVector< double > desired_state_vector
BlockVector< double > exact_coefficient_vector
SparseMatrix< double > control_mass_matrix
SparseDirectUMFPACK control_mass_inverse
std::vector< types::global_dof_index > dofs_per_block
unsigned int state_degree
unsigned int control_degree
unsigned int global_refinements
unsigned int max_pdas_iterations
double regularization
double active_set_parameter
double newton_tolerance
std::string grid_generator_function
std::string grid_generator_arguments
std::string output_name
Functions::ParsedFunction< dim > forcing_term
Functions::ParsedFunction< dim > desired_state_function
Functions::ParsedFunction< dim > reference_coefficient_function
Functions::ParsedFunction< dim > initial_coefficient_function
Functions::ParsedFunction< dim > exact_coefficient_function
Functions::ParsedFunction< dim > lower_bound_function
Functions::ParsedFunction< dim > upper_bound_function
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim>
class InversePoissonKKT< dim >
One-shot KKT solver for a coefficient-identification problem for Poisson's equation with homogeneous Dirichlet boundary conditions. The control is the diffusion coefficient, discretized with FE_DGQ on the same triangulation as state and adjoint variables.
The optimization problem is
min 1/2 ||y-y_d||^2 + alpha/2 ||a-a_ref||^2
subject to
-div(a grad y) = f in Omega, y = 0 on boundary(Omega), a_min <= a <= a_max.
Box constraints are enforced with a primal-dual active-set strategy. On each PDAS iteration we assemble the Jacobian of the all-at-once KKT system and solve the resulting linearized system with AffineConstraints<double>.
Definition at line 65 of file inverse_poisson_kkt.h.
Constructor & Destructor Documentation
InversePoissonKKT()
template<int dim> InversePoissonKKT< dim >::InversePoissonKKT (const std::string & subsection_name = "Inverse Poisson KKT problem")
Definition at line 46 of file inverse_poisson_kkt.cc.
References e(), and triangulation.
Member Function Documentation
assemble_residual_only()
template<int dim> BlockVector< double > InversePoissonKKT< dim >::assemble_residual_only (const BlockVector< double > & iterate) const private
Definition at line 493 of file inverse_poisson_kkt.cc.
References FEValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::get_function_gradients(), FEValues< int dim, int spacedim >::get_function_values(), FEValues< int dim, int spacedim >::JxW(), std::max(), FEValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), Quadrature< int dim >::size(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system()
template<int dim> void InversePoissonKKT< dim >::assemble_system () private
Definition at line 367 of file inverse_poisson_kkt.cc.
References FEValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::get_function_gradients(), FEValues< int dim, int spacedim >::get_function_values(), FEValues< int dim, int spacedim >::JxW(), std::max(), FEValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), Quadrature< int dim >::size(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
compute_lower_active_set()
template<int dim> std::vector< bool > InversePoissonKKT< dim >::compute_lower_active_set () const private
Definition at line 596 of file inverse_poisson_kkt.cc.
compute_stationarity()
template<int dim> Vector< double > InversePoissonKKT< dim >::compute_stationarity () const private
Definition at line 581 of file inverse_poisson_kkt.cc.
compute_upper_active_set()
template<int dim> std::vector< bool > InversePoissonKKT< dim >::compute_upper_active_set () const private
Definition at line 620 of file inverse_poisson_kkt.cc.
control_global_offset()
template<int dim> types::global_dof_index InversePoissonKKT< dim >::control_global_offset () const private
Definition at line 268 of file inverse_poisson_kkt.cc.
declare_parameters()
template<int dim> void InversePoissonKKT< dim >::declare_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 79 of file inverse_poisson_kkt.cc.
References ParameterHandler::add_parameter(), Functions::ParsedFunction< int dim >::declare_parameters(), ParameterHandler::enter_subsection(), ParameterHandler::leave_subsection(), and ParameterHandler::set().
enforce_box_constraints()
template<int dim> void InversePoissonKKT< dim >::enforce_box_constraints (BlockVector< double > & iterate, const std::vector< bool > & lower_active, const std::vector< bool > & upper_active) const private
Definition at line 703 of file inverse_poisson_kkt.cc.
References BlockVector< typename Number >::block().
initialize_control_mass_matrix()
template<int dim> void InversePoissonKKT< dim >::initialize_control_mass_matrix () private
Definition at line 277 of file inverse_poisson_kkt.cc.
References DynamicSparsityPattern::add(), AssertThrow, SparsityPattern::copy_from(), FEValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::JxW(), std::max(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), update_JxW_values, and update_values.
initialize_solution()
template<int dim> void InversePoissonKKT< dim >::initialize_solution () private
Definition at line 355 of file inverse_poisson_kkt.cc.
initialize_vectors()
template<int dim> void InversePoissonKKT< dim >::initialize_vectors () private
Definition at line 229 of file inverse_poisson_kkt.cc.
interpolate_component_function()
template<int dim> void InversePoissonKKT< dim >::interpolate_component_function (const Function< dim > & function, const unsigned int block, BlockVector< double > & vector) const private
Definition at line 248 of file inverse_poisson_kkt.cc.
References VectorTools::interpolate(), and Function< int dim, typename RangeNumberType >::value().
make_control_constraints()
template<int dim> AffineConstraints< double > InversePoissonKKT< dim >::make_control_constraints (const std::vector< bool > & lower_active, const std::vector< bool > & upper_active) const private
Definition at line 644 of file inverse_poisson_kkt.cc.
References AffineConstraints< typename number >::add_line(), AssertDimension, AffineConstraints< typename number >::close(), AffineConstraints< typename number >::copy_from(), AffineConstraints< typename number >::merge(), and AffineConstraints< typename number >::set_inhomogeneity().
make_grid()
template<int dim> void InversePoissonKKT< dim >::make_grid () private
Definition at line 174 of file inverse_poisson_kkt.cc.
References GridGenerator::generate_from_name_and_arguments(), and triangulation.
output_iteration()
template<int dim> std::string InversePoissonKKT< dim >::output_iteration (const unsigned int iteration, const BlockVector< double > & iterate, const std::vector< bool > & lower_active, const std::vector< bool > & upper_active) const private
Definition at line 728 of file inverse_poisson_kkt.cc.
References Utilities::int_to_string().
output_results()
template<int dim> void InversePoissonKKT< dim >::output_results (const BlockVector< double > & iterate, const std::vector< bool > & lower_active, const std::vector< bool > & upper_active, const std::string & filename) const private
Definition at line 744 of file inverse_poisson_kkt.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), BlockVector< typename Number >::block(), DataOut< int dim, int spacedim >::build_patches(), DataComponentInterpretation::component_is_scalar, and DataOut< int dim, int spacedim >::write_vtu().
parse_parameters()
template<int dim> void InversePoissonKKT< dim >::parse_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 132 of file inverse_poisson_kkt.cc.
References ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
run()
template<int dim> void InversePoissonKKT< dim >::run ()
Definition at line 834 of file inverse_poisson_kkt.cc.
References BlockVector< typename Number >::add(), AssertThrow, e(), BlockVector< typename Number >::l2_norm(), and DataOutBase::write_pvd_record().
setup_system()
template<int dim> void InversePoissonKKT< dim >::setup_system () private
Definition at line 187 of file inverse_poisson_kkt.cc.
References DoFRenumbering::component_wise(), DoFTools::count_dofs_per_fe_block(), VectorTools::interpolate_boundary_values(), DoFTools::make_hanging_node_constraints(), and DoFTools::make_sparsity_pattern().
solve_linearized_system()
template<int dim> void InversePoissonKKT< dim >::solve_linearized_system (const std::vector< bool > & lower_active, const std::vector< bool > & upper_active, BlockVector< double > & update) const private
Definition at line 677 of file inverse_poisson_kkt.cc.
References AffineConstraints< typename number >::condense(), BlockSparseMatrix< typename number >::copy_from(), AffineConstraints< typename number >::distribute(), SparseDirectUMFPACK::initialize(), BlockSparseMatrix< typename number >::reinit(), and SparseDirectUMFPACK::vmult().
Member Data Documentation
active_set_parameter
template<int dim> double InversePoissonKKT< dim >::active_set_parameter private
Definition at line 179 of file inverse_poisson_kkt.h.
adjoint_block
template<int dim> constexpr unsigned int InversePoissonKKT< dim >::adjoint_block = 1 static constexpr
Definition at line 70 of file inverse_poisson_kkt.h.
constraints
template<int dim> AffineConstraints<double> InversePoissonKKT< dim >::constraints private
Definition at line 156 of file inverse_poisson_kkt.h.
control_block
template<int dim> constexpr unsigned int InversePoissonKKT< dim >::control_block = 2 static constexpr
Definition at line 71 of file inverse_poisson_kkt.h.
control_degree
template<int dim> unsigned int InversePoissonKKT< dim >::control_degree private
Definition at line 175 of file inverse_poisson_kkt.h.
control_mass_inverse
template<int dim> SparseDirectUMFPACK InversePoissonKKT< dim >::control_mass_inverse private
Definition at line 170 of file inverse_poisson_kkt.h.
control_mass_matrix
template<int dim> SparseMatrix<double> InversePoissonKKT< dim >::control_mass_matrix private
Definition at line 169 of file inverse_poisson_kkt.h.
current_solution
template<int dim> BlockVector<double> InversePoissonKKT< dim >::current_solution private
Definition at line 160 of file inverse_poisson_kkt.h.
desired_state_function
template<int dim> Functions::ParsedFunction<dim> InversePoissonKKT< dim >::desired_state_function private
Definition at line 186 of file inverse_poisson_kkt.h.
desired_state_vector
template<int dim> BlockVector<double> InversePoissonKKT< dim >::desired_state_vector private
Definition at line 166 of file inverse_poisson_kkt.h.
dof_handler
template<int dim> DoFHandler<dim> InversePoissonKKT< dim >::dof_handler private
Definition at line 154 of file inverse_poisson_kkt.h.
dofs_per_block
template<int dim> std::vector<types::global_dof_index> InversePoissonKKT< dim >::dofs_per_block private
Definition at line 172 of file inverse_poisson_kkt.h.
exact_coefficient_function
template<int dim> Functions::ParsedFunction<dim> InversePoissonKKT< dim >::exact_coefficient_function private
Definition at line 189 of file inverse_poisson_kkt.h.
exact_coefficient_vector
template<int dim> BlockVector<double> InversePoissonKKT< dim >::exact_coefficient_vector private
Definition at line 167 of file inverse_poisson_kkt.h.
fe
template<int dim> std::unique_ptr<FESystem<dim> > InversePoissonKKT< dim >::fe private
Definition at line 153 of file inverse_poisson_kkt.h.
forcing_term
template<int dim> Functions::ParsedFunction<dim> InversePoissonKKT< dim >::forcing_term private
Definition at line 185 of file inverse_poisson_kkt.h.
global_refinements
template<int dim> unsigned int InversePoissonKKT< dim >::global_refinements private
Definition at line 176 of file inverse_poisson_kkt.h.
grid_generator_arguments
template<int dim> std::string InversePoissonKKT< dim >::grid_generator_arguments private
Definition at line 182 of file inverse_poisson_kkt.h.
grid_generator_function
template<int dim> std::string InversePoissonKKT< dim >::grid_generator_function private
Definition at line 181 of file inverse_poisson_kkt.h.
initial_coefficient_function
template<int dim> Functions::ParsedFunction<dim> InversePoissonKKT< dim >::initial_coefficient_function private
Definition at line 188 of file inverse_poisson_kkt.h.
lower_bound
template<int dim> BlockVector<double> InversePoissonKKT< dim >::lower_bound private
Definition at line 163 of file inverse_poisson_kkt.h.
lower_bound_function
template<int dim> Functions::ParsedFunction<dim> InversePoissonKKT< dim >::lower_bound_function private
Definition at line 190 of file inverse_poisson_kkt.h.
max_pdas_iterations
template<int dim> unsigned int InversePoissonKKT< dim >::max_pdas_iterations private
Definition at line 177 of file inverse_poisson_kkt.h.
n_blocks
template<int dim> constexpr unsigned int InversePoissonKKT< dim >::n_blocks = 3 static constexpr
Definition at line 68 of file inverse_poisson_kkt.h.
newton_tolerance
template<int dim> double InversePoissonKKT< dim >::newton_tolerance private
Definition at line 180 of file inverse_poisson_kkt.h.
output_name
template<int dim> std::string InversePoissonKKT< dim >::output_name private
Definition at line 183 of file inverse_poisson_kkt.h.
reference_coefficient_function
template<int dim> Functions::ParsedFunction<dim> InversePoissonKKT< dim >::reference_coefficient_function private
Definition at line 187 of file inverse_poisson_kkt.h.
reference_coefficient_vector
template<int dim> BlockVector<double> InversePoissonKKT< dim >::reference_coefficient_vector private
Definition at line 165 of file inverse_poisson_kkt.h.
regularization
template<int dim> double InversePoissonKKT< dim >::regularization private
Definition at line 178 of file inverse_poisson_kkt.h.
residual
template<int dim> BlockVector<double> InversePoissonKKT< dim >::residual private
Definition at line 162 of file inverse_poisson_kkt.h.
sparsity_pattern
template<int dim> BlockSparsityPattern InversePoissonKKT< dim >::sparsity_pattern private
Definition at line 158 of file inverse_poisson_kkt.h.
state_block
template<int dim> constexpr unsigned int InversePoissonKKT< dim >::state_block = 0 static constexpr
Definition at line 69 of file inverse_poisson_kkt.h.
state_degree
template<int dim> unsigned int InversePoissonKKT< dim >::state_degree private
Definition at line 174 of file inverse_poisson_kkt.h.
system_matrix
template<int dim> BlockSparseMatrix<double> InversePoissonKKT< dim >::system_matrix private
Definition at line 159 of file inverse_poisson_kkt.h.
system_rhs
template<int dim> BlockVector<double> InversePoissonKKT< dim >::system_rhs private
Definition at line 161 of file inverse_poisson_kkt.h.
triangulation
template<int dim> Triangulation<dim> InversePoissonKKT< dim >::triangulation private
Definition at line 151 of file inverse_poisson_kkt.h.
upper_bound
template<int dim> BlockVector<double> InversePoissonKKT< dim >::upper_bound private
Definition at line 164 of file inverse_poisson_kkt.h.
upper_bound_function
template<int dim> Functions::ParsedFunction<dim> InversePoissonKKT< dim >::upper_bound_function private
Definition at line 191 of file inverse_poisson_kkt.h.
The documentation for this class was generated from the following files:
inverse_poisson_kkt.h
inverse_poisson_kkt.cc