deal.II Testbench for NMOPT Laboratories: KKT< dim > Class Template Reference
KKT< dim > Class Template Reference
#include <kkt.h>
Public Member Functions
KKT (const std::string &subsection_name="KKT problem")
void initialize ()
void solve ()
void output_results (const std::string &filename="kkt_solution") const
void run ()
const BlockSparseMatrix< double > & get_system_matrix () const
const SparseMatrix< double > & get_system_block (const unsigned int row, const unsigned int column) const
const AffineConstraints< double > & get_constraints () const
const DoFHandler< dim > & get_dof_handler () const
const BlockVector< double > & get_system_rhs () const
const BlockVector< double > & get_solution () const
const std::vector< types::global_dof_index > & get_dofs_per_block () const
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Static Public Attributes
static constexpr unsigned int n_blocks = 3
static constexpr unsigned int state_block = 0
static constexpr unsigned int adjoint_block = 1
static constexpr unsigned int control_block = 2
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Member Functions
void declare_parameters (ParameterHandler &prm) override
void parse_parameters (ParameterHandler &prm) override
void make_grid ()
void setup_system ()
void assemble_system ()
std::unique_ptr< FESystem< dim > > create_fe_system () const
Protected Attributes
Triangulation< dim > triangulation
std::unique_ptr< FESystem< dim > > fe
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
BlockSparsityPattern sparsity_pattern
BlockSparseMatrix< double > system_matrix
BlockVector< double > solution
BlockVector< double > system_rhs
std::vector< types::global_dof_index > dofs_per_block
unsigned int state_degree
unsigned int control_degree
bool continuous_control
unsigned int global_refinements
double regularization
std::string grid_generator_function
std::string grid_generator_arguments
Functions::ParsedFunction< dim > diffusion_coefficient
Functions::ParsedFunction< dim > reaction_coefficient
Functions::ParsedFunction< dim > transport_field
Functions::ParsedFunction< dim > forcing_term
Functions::ParsedFunction< dim > desired_state
Functions::ParsedFunction< dim > state_boundary_values
Functions::ParsedFunction< dim > adjoint_boundary_values
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Detailed Description
template<int dim>
class KKT< dim >
Assemble and solve the all-at-once KKT system for a linear-quadratic PDE-constrained optimization problem.
The code looks for a state y, an adjoint p, and a control u minimizing
1/2 ||y-y_d||^2 + alpha/2 ||u||^2
subject to the diffusion-reaction-transport equation
-div(mu grad y) + beta . grad y + sigma y = u + f
with Dirichlet boundary conditions on state and adjoint.
The discrete unknown is ordered in three blocks:
block 0: state
block 1: adjoint
block 2: control
and the class assembles the full block KKT matrix so that one can access both the monolithic system and its individual blocks.
Definition at line 65 of file kkt.h.
Constructor & Destructor Documentation
KKT()
template<int dim> KKT< dim >::KKT (const std::string & subsection_name = "KKT< dim > problem")
Definition at line 40 of file kkt.cc.
References e(), and triangulation.
Member Function Documentation
assemble_system()
template<int dim> void KKT< dim >::assemble_system () protected
Definition at line 254 of file kkt.cc.
References d(), FEValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::JxW(), std::max(), FEValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
create_fe_system()
template<int dim> std::unique_ptr< FESystem< dim > > KKT< dim >::create_fe_system () const protected
Definition at line 152 of file kkt.cc.
declare_parameters()
template<int dim> void KKT< dim >::declare_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 70 of file kkt.cc.
References ParameterHandler::add_parameter(), Functions::ParsedFunction< int dim >::declare_parameters(), ParameterHandler::enter_subsection(), ParameterHandler::leave_subsection(), and ParameterHandler::set().
get_constraints()
template<int dim> const AffineConstraints< double > & KKT< dim >::get_constraints () const
Definition at line 455 of file kkt.cc.
get_dof_handler()
template<int dim> const DoFHandler< dim > & KKT< dim >::get_dof_handler () const
Definition at line 464 of file kkt.cc.
get_dofs_per_block()
template<int dim> const std::vector< types::global_dof_index > & KKT< dim >::get_dofs_per_block () const
Definition at line 491 of file kkt.cc.
get_solution()
template<int dim> const BlockVector< double > & KKT< dim >::get_solution () const
Definition at line 482 of file kkt.cc.
get_system_block()
template<int dim> const SparseMatrix< double > & KKT< dim >::get_system_block (const unsigned int row, const unsigned int column) const
Definition at line 443 of file kkt.cc.
References AssertIndexRange.
get_system_matrix()
template<int dim> const BlockSparseMatrix< double > & KKT< dim >::get_system_matrix () const
Definition at line 434 of file kkt.cc.
get_system_rhs()
template<int dim> const BlockVector< double > & KKT< dim >::get_system_rhs () const
Definition at line 473 of file kkt.cc.
initialize()
template<int dim> void KKT< dim >::initialize ()
Definition at line 187 of file kkt.cc.
make_grid()
template<int dim> void KKT< dim >::make_grid () protected
Definition at line 174 of file kkt.cc.
References GridGenerator::generate_from_name_and_arguments(), and triangulation.
output_results()
template<int dim> void KKT< dim >::output_results (const std::string & filename = "kkt_solution") const
Definition at line 362 of file kkt.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), DataComponentInterpretation::component_is_scalar, VectorTools::interpolate(), BlockVector< typename Number >::reinit(), and DataOut< int dim, int spacedim >::write_vtu().
parse_parameters()
template<int dim> void KKT< dim >::parse_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 115 of file kkt.cc.
References ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
run()
template<int dim> void KKT< dim >::run ()
Definition at line 412 of file kkt.cc.
References triangulation.
setup_system()
template<int dim> void KKT< dim >::setup_system () protected
Definition at line 198 of file kkt.cc.
References DoFRenumbering::component_wise(), DoFTools::count_dofs_per_fe_block(), VectorTools::interpolate_boundary_values(), DoFTools::make_hanging_node_constraints(), and DoFTools::make_sparsity_pattern().
solve()
template<int dim> void KKT< dim >::solve ()
Definition at line 400 of file kkt.cc.
References SparseDirectUMFPACK::initialize(), and SparseDirectUMFPACK::vmult().
Member Data Documentation
adjoint_block
template<int dim> constexpr unsigned int KKT< dim >::adjoint_block = 1 static constexpr
Definition at line 70 of file kkt.h.
adjoint_boundary_values
template<int dim> Functions::ParsedFunction<dim> KKT< dim >::adjoint_boundary_values protected
Definition at line 155 of file kkt.h.
constraints
template<int dim> AffineConstraints<double> KKT< dim >::constraints protected
Definition at line 132 of file kkt.h.
continuous_control
template<int dim> bool KKT< dim >::continuous_control protected
Definition at line 143 of file kkt.h.
control_block
template<int dim> constexpr unsigned int KKT< dim >::control_block = 2 static constexpr
Definition at line 71 of file kkt.h.
control_degree
template<int dim> unsigned int KKT< dim >::control_degree protected
Definition at line 142 of file kkt.h.
desired_state
template<int dim> Functions::ParsedFunction<dim> KKT< dim >::desired_state protected
Definition at line 153 of file kkt.h.
diffusion_coefficient
template<int dim> Functions::ParsedFunction<dim> KKT< dim >::diffusion_coefficient protected
Definition at line 149 of file kkt.h.
dof_handler
template<int dim> DoFHandler<dim> KKT< dim >::dof_handler protected
Definition at line 130 of file kkt.h.
dofs_per_block
template<int dim> std::vector<types::global_dof_index> KKT< dim >::dofs_per_block protected
Definition at line 139 of file kkt.h.
fe
template<int dim> std::unique_ptr<FESystem<dim> > KKT< dim >::fe protected
Definition at line 129 of file kkt.h.
forcing_term
template<int dim> Functions::ParsedFunction<dim> KKT< dim >::forcing_term protected
Definition at line 152 of file kkt.h.
global_refinements
template<int dim> unsigned int KKT< dim >::global_refinements protected
Definition at line 144 of file kkt.h.
grid_generator_arguments
template<int dim> std::string KKT< dim >::grid_generator_arguments protected
Definition at line 147 of file kkt.h.
grid_generator_function
template<int dim> std::string KKT< dim >::grid_generator_function protected
Definition at line 146 of file kkt.h.
n_blocks
template<int dim> constexpr unsigned int KKT< dim >::n_blocks = 3 static constexpr
Definition at line 68 of file kkt.h.
reaction_coefficient
template<int dim> Functions::ParsedFunction<dim> KKT< dim >::reaction_coefficient protected
Definition at line 150 of file kkt.h.
regularization
template<int dim> double KKT< dim >::regularization protected
Definition at line 145 of file kkt.h.
solution
template<int dim> BlockVector<double> KKT< dim >::solution protected
Definition at line 136 of file kkt.h.
sparsity_pattern
template<int dim> BlockSparsityPattern KKT< dim >::sparsity_pattern protected
Definition at line 134 of file kkt.h.
state_block
template<int dim> constexpr unsigned int KKT< dim >::state_block = 0 static constexpr
Definition at line 69 of file kkt.h.
state_boundary_values
template<int dim> Functions::ParsedFunction<dim> KKT< dim >::state_boundary_values protected
Definition at line 154 of file kkt.h.
state_degree
template<int dim> unsigned int KKT< dim >::state_degree protected
Definition at line 141 of file kkt.h.
system_matrix
template<int dim> BlockSparseMatrix<double> KKT< dim >::system_matrix protected
Definition at line 135 of file kkt.h.
system_rhs
template<int dim> BlockVector<double> KKT< dim >::system_rhs protected
Definition at line 137 of file kkt.h.
transport_field
template<int dim> Functions::ParsedFunction<dim> KKT< dim >::transport_field protected
Definition at line 151 of file kkt.h.
triangulation
template<int dim> Triangulation<dim> KKT< dim >::triangulation protected
Definition at line 127 of file kkt.h.
The documentation for this class was generated from the following files:
kkt.h
kkt.cc