deal.II Testbench for NMOPT Laboratories: ParabolicProjectedGradient< dim > Class Template Reference
ParabolicProjectedGradient< dim > Class Template Reference
#include <parabolic_projected_gradient.h>
Classes
struct Diagnostics
Public Member Functions
ParabolicProjectedGradient (const std::string &subsection_name="Parabolic projected-gradient problem")
void initialize ()
void run ()
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Static Public Attributes
static constexpr unsigned int n_blocks = 3
static constexpr unsigned int state_block = 0
static constexpr unsigned int adjoint_block = 1
static constexpr unsigned int control_block = 2
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Member Functions
void declare_parameters (ParameterHandler &prm) override
void parse_parameters (ParameterHandler &prm) override
Private Types
using TimeVector = std::vector< Vector< double > >
Private Member Functions
void make_grid ()
void setup_system ()
void assemble_matrices ()
void initialize_time_step_solvers ()
std::unique_ptr< FESystem< dim > > create_fe_system () const
void reinit_time_vector (TimeVector &values, const unsigned int block, const bool include_terminal_slot=false) const
void interpolate_function_to_block (Functions::ParsedFunction< dim > &function, const unsigned int block, const double time, Vector< double > &vector) const
void distribute_block (const unsigned int block, Vector< double > &vector) const
void initialize_time_data ()
void initialize_control (TimeVector &control) const
void project_onto_box (TimeVector &control) const
void project_time_level (const unsigned int time_index, Vector< double > &control) const
void solve_state (const TimeVector &control, TimeVector &state) const
void solve_adjoint (const TimeVector &state, TimeVector &adjoint) const
void compute_gradient (const TimeVector &control, const TimeVector &adjoint, TimeVector &gradient) const
void projected_gradient_step (TimeVector &trial_control, const TimeVector &gradient, const double step_length) const
double control_inner_product (const TimeVector &left, const TimeVector &right) const
double control_norm (const TimeVector &control) const
Diagnostics compute_diagnostics (const TimeVector &state, const TimeVector &control, const TimeVector &gradient, const double step_length) const
double compute_projected_gradient_norm (const TimeVector &control, const TimeVector &gradient, const double step_length) const
double choose_step_length (const TimeVector &control, const TimeVector &gradient, const Diagnostics &diagnostics) const
void output_time_sequence (const unsigned int iteration, const TimeVector &state, const TimeVector &adjoint, const TimeVector &control) const
void write_csv_header (std::ofstream &csv) const
void write_csv_line (std::ofstream &csv, const unsigned int iteration, const Diagnostics &diagnostics) const
Static Private Member Functions
static std::string default_variable_names ()
Private Attributes
Triangulation< dim > triangulation
std::unique_ptr< FESystem< dim > > fe
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
BlockSparsityPattern sparsity_pattern
BlockSparseMatrix< double > mass_matrix
BlockSparseMatrix< double > stiffness_matrix
BlockSparseMatrix< double > coupling_matrix
BlockSparseMatrix< double > tracking_matrix
SparseMatrix< double > state_time_step_matrix
SparseMatrix< double > adjoint_time_step_matrix
SparseDirectUMFPACK state_time_step_inverse
SparseDirectUMFPACK adjoint_time_step_inverse
SparseDirectUMFPACK control_mass_inverse
std::vector< types::global_dof_index > dofs_per_block
TimeVector lower_bound
TimeVector upper_bound
TimeVector target_state
Vector< double > terminal_target
unsigned int state_degree
unsigned int control_degree
bool continuous_control
unsigned int global_refinements
double final_time
unsigned int n_time_steps
double time_step
double regularization
double terminal_tracking_weight
unsigned int max_iterations
double gradient_tolerance
double projected_gradient_tolerance
double fixed_step_length
std::string output_name
std::string grid_generator_function
std::string grid_generator_arguments
OptimizationTools::ArmijoParameters< double > armijo_parameters
Functions::ParsedFunction< dim > diffusion_coefficient
Functions::ParsedFunction< dim > reaction_coefficient
Functions::ParsedFunction< dim > forcing_term
Functions::ParsedFunction< dim > initial_state
Functions::ParsedFunction< dim > initial_control
Functions::ParsedFunction< dim > desired_state
Functions::ParsedFunction< dim > terminal_target_function
Functions::ParsedFunction< dim > lower_bound_function
Functions::ParsedFunction< dim > upper_bound_function
Functions::ParsedFunction< dim > state_boundary_values
Functions::ParsedFunction< dim > adjoint_boundary_values
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int dim>
class ParabolicProjectedGradient< dim >
Reduced projected-gradient solver for a linear-quadratic parabolic optimal control problem.
The time discretization is implicit Euler. For a fixed control sequence the state is propagated forward in time, the adjoint is propagated backward in time, and the control is updated by a box-projected gradient step.
The finite element system has three components:
block 0: state space;
block 1: adjoint space;
block 2: control space.
The state and adjoint spaces are continuous FE_Q spaces. The control space can be either continuous FE_Q or discontinuous FE_DGQ, as in the elliptic laboratories.
Definition at line 67 of file parabolic_projected_gradient.h.
Member Typedef Documentation
TimeVector
template<int dim> using ParabolicProjectedGradient< dim >::TimeVector = std::vector<Vector<double> > private
Definition at line 104 of file parabolic_projected_gradient.h.
Constructor & Destructor Documentation
ParabolicProjectedGradient()
template<int dim> ParabolicProjectedGradient< dim >::ParabolicProjectedGradient (const std::string & subsection_name = "Parabolic projected-gradient problem")
Definition at line 43 of file parabolic_projected_gradient.cc.
References e(), and triangulation.
Member Function Documentation
assemble_matrices()
template<int dim> void ParabolicProjectedGradient< dim >::assemble_matrices () private
Definition at line 378 of file parabolic_projected_gradient.cc.
References FEValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::JxW(), std::max(), FEValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
choose_step_length()
template<int dim> double ParabolicProjectedGradient< dim >::choose_step_length (const TimeVector & control, const TimeVector & gradient, const Diagnostics & diagnostics) const private
Definition at line 884 of file parabolic_projected_gradient.cc.
compute_diagnostics()
template<int dim> ParabolicProjectedGradient< dim >::Diagnostics ParabolicProjectedGradient< dim >::compute_diagnostics (const TimeVector & state, const TimeVector & control, const TimeVector & gradient, const double step_length) const private
Definition at line 813 of file parabolic_projected_gradient.cc.
References ParabolicProjectedGradient< dim >::Diagnostics::control_cost, ParabolicProjectedGradient< dim >::Diagnostics::control_norm, ParabolicProjectedGradient< dim >::Diagnostics::cost, ParabolicProjectedGradient< dim >::Diagnostics::gradient_norm, ParabolicProjectedGradient< dim >::Diagnostics::projected_gradient_norm, ParabolicProjectedGradient< dim >::Diagnostics::step_length, ParabolicProjectedGradient< dim >::Diagnostics::terminal_tracking_cost, and ParabolicProjectedGradient< dim >::Diagnostics::tracking_cost.
compute_gradient()
template<int dim> void ParabolicProjectedGradient< dim >::compute_gradient (const TimeVector & control, const TimeVector & adjoint, TimeVector & gradient) const private
Definition at line 738 of file parabolic_projected_gradient.cc.
compute_projected_gradient_norm()
template<int dim> double ParabolicProjectedGradient< dim >::compute_projected_gradient_norm (const TimeVector & control, const TimeVector & gradient, const double step_length) const private
Definition at line 862 of file parabolic_projected_gradient.cc.
control_inner_product()
template<int dim> double ParabolicProjectedGradient< dim >::control_inner_product (const TimeVector & left, const TimeVector & right) const private
Definition at line 784 of file parabolic_projected_gradient.cc.
control_norm()
template<int dim> double ParabolicProjectedGradient< dim >::control_norm (const TimeVector & control) const private
Definition at line 804 of file parabolic_projected_gradient.cc.
References std::max(), and std::sqrt().
create_fe_system()
template<int dim> std::unique_ptr< FESystem< dim > > ParabolicProjectedGradient< dim >::create_fe_system () const private
Definition at line 263 of file parabolic_projected_gradient.cc.
declare_parameters()
template<int dim> void ParabolicProjectedGradient< dim >::declare_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 103 of file parabolic_projected_gradient.cc.
References ParameterHandler::add_parameter(), Functions::ParsedFunction< int dim >::declare_parameters(), ParameterHandler::enter_subsection(), ParameterHandler::leave_subsection(), and ParameterHandler::set().
default_variable_names()
template<int dim> std::string ParabolicProjectedGradient< dim >::default_variable_names () static private
Definition at line 87 of file parabolic_projected_gradient.cc.
References d().
distribute_block()
template<int dim> void ParabolicProjectedGradient< dim >::distribute_block (const unsigned int block, Vector< double > & vector) const private
Definition at line 552 of file parabolic_projected_gradient.cc.
References BlockVector< typename Number >::block().
initialize()
template<int dim> void ParabolicProjectedGradient< dim >::initialize ()
Definition at line 307 of file parabolic_projected_gradient.cc.
initialize_control()
template<int dim> void ParabolicProjectedGradient< dim >::initialize_control (TimeVector & control) const private
Definition at line 606 of file parabolic_projected_gradient.cc.
References ParabolicProjectedGradient< dim >::interpolate_function_to_block().
initialize_time_data()
template<int dim> void ParabolicProjectedGradient< dim >::initialize_time_data () private
Definition at line 566 of file parabolic_projected_gradient.cc.
References AssertThrow.
initialize_time_step_solvers()
template<int dim> void ParabolicProjectedGradient< dim >::initialize_time_step_solvers () private
Definition at line 485 of file parabolic_projected_gradient.cc.
interpolate_function_to_block()
template<int dim> void ParabolicProjectedGradient< dim >::interpolate_function_to_block (Functions::ParsedFunction< dim > & function, const unsigned int block, const double time, Vector< double > & vector) const private
Definition at line 528 of file parabolic_projected_gradient.cc.
References BlockVector< typename Number >::block(), VectorTools::interpolate(), Functions::ParsedFunction< int dim >::set_time(), and Functions::ParsedFunction< int dim >::value().
Referenced by ParabolicProjectedGradient< dim >::initialize_control().
make_grid()
template<int dim> void ParabolicProjectedGradient< dim >::make_grid () private
Definition at line 285 of file parabolic_projected_gradient.cc.
References deallog, GridGenerator::generate_from_name_and_arguments(), Patterns::Tools::to_string(), and triangulation.
output_time_sequence()
template<int dim> void ParabolicProjectedGradient< dim >::output_time_sequence (const unsigned int iteration, const TimeVector & state, const TimeVector & adjoint, const TimeVector & control) const private
Definition at line 900 of file parabolic_projected_gradient.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), BlockVector< typename Number >::block(), DataOut< int dim, int spacedim >::build_patches(), DataComponentInterpretation::component_is_scalar, Utilities::int_to_string(), DataOutBase::write_pvd_record(), and DataOut< int dim, int spacedim >::write_vtu().
parse_parameters()
template<int dim> void ParabolicProjectedGradient< dim >::parse_parameters (ParameterHandler & prm) override protected virtual
Reimplemented from ParameterAcceptor.
Definition at line 201 of file parabolic_projected_gradient.cc.
References AssertThrow, ParameterHandler::enter_subsection(), and ParameterHandler::leave_subsection().
project_onto_box()
template<int dim> void ParabolicProjectedGradient< dim >::project_onto_box (TimeVector & control) const private
Definition at line 625 of file parabolic_projected_gradient.cc.
project_time_level()
template<int dim> void ParabolicProjectedGradient< dim >::project_time_level (const unsigned int time_index, Vector< double > & control) const private
Definition at line 635 of file parabolic_projected_gradient.cc.
References Vector< typename Number >::size().
projected_gradient_step()
template<int dim> void ParabolicProjectedGradient< dim >::projected_gradient_step (TimeVector & trial_control, const TimeVector & gradient, const double step_length) const private
Definition at line 766 of file parabolic_projected_gradient.cc.
reinit_time_vector()
template<int dim> void ParabolicProjectedGradient< dim >::reinit_time_vector (TimeVector & values, const unsigned int block, const bool include_terminal_slot = false) const private
Definition at line 511 of file parabolic_projected_gradient.cc.
run()
template<int dim> void ParabolicProjectedGradient< dim >::run ()
Definition at line 1014 of file parabolic_projected_gradient.cc.
References ParabolicProjectedGradient< dim >::Diagnostics::cost, ParabolicProjectedGradient< dim >::Diagnostics::gradient_norm, ParabolicProjectedGradient< dim >::Diagnostics::projected_gradient_norm, ParabolicProjectedGradient< dim >::Diagnostics::step_length, and triangulation.
setup_system()
template<int dim> void ParabolicProjectedGradient< dim >::setup_system () private
Definition at line 320 of file parabolic_projected_gradient.cc.
References DoFRenumbering::component_wise(), DoFTools::count_dofs_per_fe_block(), VectorTools::interpolate_boundary_values(), DoFTools::make_hanging_node_constraints(), and DoFTools::make_sparsity_pattern().
solve_adjoint()
template<int dim> void ParabolicProjectedGradient< dim >::solve_adjoint (const TimeVector & state, TimeVector & adjoint) const private
Definition at line 696 of file parabolic_projected_gradient.cc.
References Vector< typename Number >::add().
solve_state()
template<int dim> void ParabolicProjectedGradient< dim >::solve_state (const TimeVector & control, TimeVector & state) const private
Definition at line 651 of file parabolic_projected_gradient.cc.
write_csv_header()
template<int dim> void ParabolicProjectedGradient< dim >::write_csv_header (std::ofstream & csv) const private
Definition at line 988 of file parabolic_projected_gradient.cc.
write_csv_line()
template<int dim> void ParabolicProjectedGradient< dim >::write_csv_line (std::ofstream & csv, const unsigned int iteration, const Diagnostics & diagnostics) const private
Definition at line 998 of file parabolic_projected_gradient.cc.
References ParabolicProjectedGradient< dim >::Diagnostics::control_cost, ParabolicProjectedGradient< dim >::Diagnostics::control_norm, ParabolicProjectedGradient< dim >::Diagnostics::cost, ParabolicProjectedGradient< dim >::Diagnostics::gradient_norm, ParabolicProjectedGradient< dim >::Diagnostics::projected_gradient_norm, ParabolicProjectedGradient< dim >::Diagnostics::step_length, ParabolicProjectedGradient< dim >::Diagnostics::terminal_tracking_cost, and ParabolicProjectedGradient< dim >::Diagnostics::tracking_cost.
Member Data Documentation
adjoint_block
template<int dim> constexpr unsigned int ParabolicProjectedGradient< dim >::adjoint_block = 1 static constexpr
Definition at line 72 of file parabolic_projected_gradient.h.
adjoint_boundary_values
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::adjoint_boundary_values private
Definition at line 261 of file parabolic_projected_gradient.h.
adjoint_time_step_inverse
template<int dim> SparseDirectUMFPACK ParabolicProjectedGradient< dim >::adjoint_time_step_inverse private
Definition at line 220 of file parabolic_projected_gradient.h.
adjoint_time_step_matrix
template<int dim> SparseMatrix<double> ParabolicProjectedGradient< dim >::adjoint_time_step_matrix private
Definition at line 217 of file parabolic_projected_gradient.h.
armijo_parameters
template<int dim> OptimizationTools::ArmijoParameters<double> ParabolicProjectedGradient< dim >::armijo_parameters private
Definition at line 249 of file parabolic_projected_gradient.h.
constraints
template<int dim> AffineConstraints<double> ParabolicProjectedGradient< dim >::constraints private
Definition at line 208 of file parabolic_projected_gradient.h.
continuous_control
template<int dim> bool ParabolicProjectedGradient< dim >::continuous_control private
Definition at line 232 of file parabolic_projected_gradient.h.
control_block
template<int dim> constexpr unsigned int ParabolicProjectedGradient< dim >::control_block = 2 static constexpr
Definition at line 73 of file parabolic_projected_gradient.h.
control_degree
template<int dim> unsigned int ParabolicProjectedGradient< dim >::control_degree private
Definition at line 231 of file parabolic_projected_gradient.h.
control_mass_inverse
template<int dim> SparseDirectUMFPACK ParabolicProjectedGradient< dim >::control_mass_inverse private
Definition at line 221 of file parabolic_projected_gradient.h.
coupling_matrix
template<int dim> BlockSparseMatrix<double> ParabolicProjectedGradient< dim >::coupling_matrix private
Definition at line 213 of file parabolic_projected_gradient.h.
desired_state
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::desired_state private
Definition at line 256 of file parabolic_projected_gradient.h.
diffusion_coefficient
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::diffusion_coefficient private
Definition at line 251 of file parabolic_projected_gradient.h.
dof_handler
template<int dim> DoFHandler<dim> ParabolicProjectedGradient< dim >::dof_handler private
Definition at line 206 of file parabolic_projected_gradient.h.
dofs_per_block
template<int dim> std::vector<types::global_dof_index> ParabolicProjectedGradient< dim >::dofs_per_block private
Definition at line 223 of file parabolic_projected_gradient.h.
fe
template<int dim> std::unique_ptr<FESystem<dim> > ParabolicProjectedGradient< dim >::fe private
Definition at line 205 of file parabolic_projected_gradient.h.
final_time
template<int dim> double ParabolicProjectedGradient< dim >::final_time private
Definition at line 235 of file parabolic_projected_gradient.h.
fixed_step_length
template<int dim> double ParabolicProjectedGradient< dim >::fixed_step_length private
Definition at line 244 of file parabolic_projected_gradient.h.
forcing_term
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::forcing_term private
Definition at line 253 of file parabolic_projected_gradient.h.
global_refinements
template<int dim> unsigned int ParabolicProjectedGradient< dim >::global_refinements private
Definition at line 233 of file parabolic_projected_gradient.h.
gradient_tolerance
template<int dim> double ParabolicProjectedGradient< dim >::gradient_tolerance private
Definition at line 242 of file parabolic_projected_gradient.h.
grid_generator_arguments
template<int dim> std::string ParabolicProjectedGradient< dim >::grid_generator_arguments private
Definition at line 247 of file parabolic_projected_gradient.h.
grid_generator_function
template<int dim> std::string ParabolicProjectedGradient< dim >::grid_generator_function private
Definition at line 246 of file parabolic_projected_gradient.h.
initial_control
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::initial_control private
Definition at line 255 of file parabolic_projected_gradient.h.
initial_state
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::initial_state private
Definition at line 254 of file parabolic_projected_gradient.h.
lower_bound
template<int dim> TimeVector ParabolicProjectedGradient< dim >::lower_bound private
Definition at line 225 of file parabolic_projected_gradient.h.
lower_bound_function
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::lower_bound_function private
Definition at line 258 of file parabolic_projected_gradient.h.
mass_matrix
template<int dim> BlockSparseMatrix<double> ParabolicProjectedGradient< dim >::mass_matrix private
Definition at line 211 of file parabolic_projected_gradient.h.
max_iterations
template<int dim> unsigned int ParabolicProjectedGradient< dim >::max_iterations private
Definition at line 241 of file parabolic_projected_gradient.h.
n_blocks
template<int dim> constexpr unsigned int ParabolicProjectedGradient< dim >::n_blocks = 3 static constexpr
Definition at line 70 of file parabolic_projected_gradient.h.
n_time_steps
template<int dim> unsigned int ParabolicProjectedGradient< dim >::n_time_steps private
Definition at line 236 of file parabolic_projected_gradient.h.
output_name
template<int dim> std::string ParabolicProjectedGradient< dim >::output_name private
Definition at line 245 of file parabolic_projected_gradient.h.
projected_gradient_tolerance
template<int dim> double ParabolicProjectedGradient< dim >::projected_gradient_tolerance private
Definition at line 243 of file parabolic_projected_gradient.h.
reaction_coefficient
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::reaction_coefficient private
Definition at line 252 of file parabolic_projected_gradient.h.
regularization
template<int dim> double ParabolicProjectedGradient< dim >::regularization private
Definition at line 239 of file parabolic_projected_gradient.h.
sparsity_pattern
template<int dim> BlockSparsityPattern ParabolicProjectedGradient< dim >::sparsity_pattern private
Definition at line 210 of file parabolic_projected_gradient.h.
state_block
template<int dim> constexpr unsigned int ParabolicProjectedGradient< dim >::state_block = 0 static constexpr
Definition at line 71 of file parabolic_projected_gradient.h.
state_boundary_values
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::state_boundary_values private
Definition at line 260 of file parabolic_projected_gradient.h.
state_degree
template<int dim> unsigned int ParabolicProjectedGradient< dim >::state_degree private
Definition at line 230 of file parabolic_projected_gradient.h.
state_time_step_inverse
template<int dim> SparseDirectUMFPACK ParabolicProjectedGradient< dim >::state_time_step_inverse private
Definition at line 219 of file parabolic_projected_gradient.h.
state_time_step_matrix
template<int dim> SparseMatrix<double> ParabolicProjectedGradient< dim >::state_time_step_matrix private
Definition at line 216 of file parabolic_projected_gradient.h.
stiffness_matrix
template<int dim> BlockSparseMatrix<double> ParabolicProjectedGradient< dim >::stiffness_matrix private
Definition at line 212 of file parabolic_projected_gradient.h.
target_state
template<int dim> TimeVector ParabolicProjectedGradient< dim >::target_state private
Definition at line 227 of file parabolic_projected_gradient.h.
terminal_target
template<int dim> Vector<double> ParabolicProjectedGradient< dim >::terminal_target private
Definition at line 228 of file parabolic_projected_gradient.h.
terminal_target_function
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::terminal_target_function private
Definition at line 257 of file parabolic_projected_gradient.h.
terminal_tracking_weight
template<int dim> double ParabolicProjectedGradient< dim >::terminal_tracking_weight private
Definition at line 240 of file parabolic_projected_gradient.h.
time_step
template<int dim> double ParabolicProjectedGradient< dim >::time_step private
Definition at line 237 of file parabolic_projected_gradient.h.
tracking_matrix
template<int dim> BlockSparseMatrix<double> ParabolicProjectedGradient< dim >::tracking_matrix private
Definition at line 214 of file parabolic_projected_gradient.h.
triangulation
template<int dim> Triangulation<dim> ParabolicProjectedGradient< dim >::triangulation private
Definition at line 203 of file parabolic_projected_gradient.h.
upper_bound
template<int dim> TimeVector ParabolicProjectedGradient< dim >::upper_bound private
Definition at line 226 of file parabolic_projected_gradient.h.
upper_bound_function
template<int dim> Functions::ParsedFunction<dim> ParabolicProjectedGradient< dim >::upper_bound_function private
Definition at line 259 of file parabolic_projected_gradient.h.
The documentation for this class was generated from the following files:
parabolic_projected_gradient.h
parabolic_projected_gradient.cc