deal.II Testbench for NMOPT Laboratories: OptimizationTools::ArmijoParameters< Number > Struct Template Reference
OptimizationTools::ArmijoParameters< Number > Struct Template Reference
#include <optimization_tools.h>
Public Member Functions
void add_parameters (ParameterHandler &prm)
Public Attributes
Number alpha0 = Number(1.)
Number c1 = Number(1.e-4)
Number beta = Number(0.5)
unsigned int max_backtracks = 30
Number minimum_alpha = Number(1.e-16)
Detailed Description
template<typename Number>
struct OptimizationTools::ArmijoParameters< Number >
Common parameters for Armijo backtracking.
Definition at line 42 of file optimization_tools.h.
Member Function Documentation
add_parameters()
template<typename Number > void OptimizationTools::ArmijoParameters< Number >::add_parameters (ParameterHandler & prm) inline
Definition at line 51 of file optimization_tools.h.
References ParameterHandler::add_parameter(), OptimizationTools::ArmijoParameters< Number >::alpha0, OptimizationTools::ArmijoParameters< Number >::beta, OptimizationTools::ArmijoParameters< Number >::c1, OptimizationTools::ArmijoParameters< Number >::max_backtracks, and OptimizationTools::ArmijoParameters< Number >::minimum_alpha.
Member Data Documentation
alpha0
template<typename Number > Number OptimizationTools::ArmijoParameters< Number >::alpha0 = Number(1.)
Definition at line 44 of file optimization_tools.h.
Referenced by OptimizationTools::ArmijoParameters< Number >::add_parameters().
beta
template<typename Number > Number OptimizationTools::ArmijoParameters< Number >::beta = Number(0.5)
Definition at line 46 of file optimization_tools.h.
Referenced by OptimizationTools::ArmijoParameters< Number >::add_parameters().
c1
template<typename Number > Number OptimizationTools::ArmijoParameters< Number >::c1 = Number(1.e-4)
Definition at line 45 of file optimization_tools.h.
Referenced by OptimizationTools::ArmijoParameters< Number >::add_parameters().
max_backtracks
template<typename Number > unsigned int OptimizationTools::ArmijoParameters< Number >::max_backtracks = 30
Definition at line 47 of file optimization_tools.h.
Referenced by OptimizationTools::ArmijoParameters< Number >::add_parameters().
minimum_alpha
template<typename Number > Number OptimizationTools::ArmijoParameters< Number >::minimum_alpha = Number(1.e-16)
Definition at line 48 of file optimization_tools.h.
Referenced by OptimizationTools::ArmijoParameters< Number >::add_parameters().
The documentation for this struct was generated from the following file:
optimization_tools.h