deal.II Testbench for NMOPT Laboratories: OptimizationTools::OptimizationParameters< Number > Struct Template Reference
OptimizationTools::OptimizationParameters< Number > Struct Template Reference
#include <optimization_tools.h>
Public Member Functions
void add_parameters (ParameterHandler &prm)
Public Attributes
unsigned int max_iterations = 200
Number gradient_tolerance = Number(1.e-8)
bool store_iterates = true
bool log_iterations = true
ArmijoParameters< Number > armijo
Detailed Description
template<typename Number>
struct OptimizationTools::OptimizationParameters< Number >
Generic stopping and logging parameters for unconstrained optimization algorithms.
Definition at line 67 of file optimization_tools.h.
Member Function Documentation
add_parameters()
template<typename Number > void OptimizationTools::OptimizationParameters< Number >::add_parameters (ParameterHandler & prm) inline
Definition at line 76 of file optimization_tools.h.
References ParameterHandler::add_parameter(), OptimizationTools::OptimizationParameters< Number >::armijo, ParameterHandler::enter_subsection(), OptimizationTools::OptimizationParameters< Number >::gradient_tolerance, ParameterHandler::leave_subsection(), OptimizationTools::OptimizationParameters< Number >::log_iterations, OptimizationTools::OptimizationParameters< Number >::max_iterations, and OptimizationTools::OptimizationParameters< Number >::store_iterates.
Referenced by OptimizationTools::NLCGParameters< Number >::add_parameters(), OptimizationTools::LBFGSParameters< Number >::add_parameters(), and OptimizationTools::TrustRegionParameters< Number >::add_parameters().
Member Data Documentation
armijo
template<typename Number > ArmijoParameters<Number> OptimizationTools::OptimizationParameters< Number >::armijo
Definition at line 73 of file optimization_tools.h.
Referenced by OptimizationTools::OptimizationParameters< Number >::add_parameters().
gradient_tolerance
template<typename Number > Number OptimizationTools::OptimizationParameters< Number >::gradient_tolerance = Number(1.e-8)
Definition at line 70 of file optimization_tools.h.
Referenced by OptimizationTools::OptimizationParameters< Number >::add_parameters().
log_iterations
template<typename Number > bool OptimizationTools::OptimizationParameters< Number >::log_iterations = true
Definition at line 72 of file optimization_tools.h.
Referenced by OptimizationTools::OptimizationParameters< Number >::add_parameters().
max_iterations
template<typename Number > unsigned int OptimizationTools::OptimizationParameters< Number >::max_iterations = 200
Definition at line 69 of file optimization_tools.h.
Referenced by OptimizationTools::OptimizationParameters< Number >::add_parameters().
store_iterates
template<typename Number > bool OptimizationTools::OptimizationParameters< Number >::store_iterates = true
Definition at line 71 of file optimization_tools.h.
Referenced by OptimizationTools::OptimizationParameters< Number >::add_parameters().
The documentation for this struct was generated from the following file:
optimization_tools.h