name: deal.II Indent

on:
  push:
    branches: [main]
    paths:
      - "codes/dealii/**"
      - ".github/workflows/dealii-indentation.yml"
  pull_request:
    branches: [main]
    paths:
      - "codes/dealii/**"
      - ".github/workflows/dealii-indentation.yml"

jobs:
  indent:
    runs-on: ubuntu-latest
    container:
      image: dealii/dealii:v9.7.1-noble
      options: --user root
    defaults:
      run:
        working-directory: codes/dealii

    steps:
      - uses: actions/checkout@v4
      - name: Check indentation
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./scripts/check_indentation.sh
